/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2016 Gareth Jon Lynch
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.gazbert.patterns.behavioural.chainofresponsibility;

import static org.junit.Assert.*;

import org.junit.Test;

/**
 * Demonstrates use of Chain of Responsibility pattern.
 *
 * @author gazbert
 */
public class TestChainOfResponsibilityPattern {
    /**
     * Pretend this test is a newly document review request generated by something like JIRA/Bugzilla.
     */
    @Test
    public void testStatePattern() {

        String document = "New sales targets for 2nd quarter.";
        AbstractDocumentReviewHandler.reviewDocumentRequest(document);
        assertEquals("sales", AbstractDocumentReviewHandler.getHandledBy());

        document = "Iteration plan for developing Video Calling feature.";
        AbstractDocumentReviewHandler.reviewDocumentRequest(document);
        assertEquals("engineering", AbstractDocumentReviewHandler.getHandledBy());

        document = "Integration test plan for Citi.";
        AbstractDocumentReviewHandler.reviewDocumentRequest(document);
        assertEquals("testing", AbstractDocumentReviewHandler.getHandledBy());

        document = "New support escalation procedures for JP Morgan";
        AbstractDocumentReviewHandler.reviewDocumentRequest(document);
        assertEquals("support", AbstractDocumentReviewHandler.getHandledBy());
    }
}
