package com.gazbert.patterns.behavioural.chainofresponsibility;

import static org.junit.Assert.*;

import org.junit.Test;

/**
 * Demonstrates use of Chain of Responsibility pattern.
 * 
 * @author gazbert
 *
 */
public class TestChainOfResponsibilityPattern 
{
    /**
     * Pretend this test is a newly document review request generated by something like JIRA/Bugzilla. 
     */
    @Test
    public void testStatePattern() {

        String document = "New sales targets for 2nd quarter.";
        AbstractDocumentReviewHandler.reviewDocumentRequest(document);
        assertEquals("sales", AbstractDocumentReviewHandler.getHandledBy());

        document = "Iteration plan for developing Video Calling feature.";
        AbstractDocumentReviewHandler.reviewDocumentRequest(document);
        assertEquals("engineering", AbstractDocumentReviewHandler.getHandledBy());

        document = "Integration test plan for Citi.";
        AbstractDocumentReviewHandler.reviewDocumentRequest(document);
        assertEquals("testing", AbstractDocumentReviewHandler.getHandledBy());

        document = "New support escalation procedures for JP Morgan";
        AbstractDocumentReviewHandler.reviewDocumentRequest(document);
        assertEquals("support", AbstractDocumentReviewHandler.getHandledBy());	
    }
}
